import type { VRMHumanBoneName } from "@pixiv/three-vrm";

/**
 * Mapping from Blender bone names to VRM human bone names
 * Used for retargeting animations from Blender rigs to VRM avatars
 */
export const boneMap: Record<string, VRMHumanBoneName> = {
  "DEF-hips": "hips",
  "DEF-spine001": "spine",
  "DEF-spine002": "chest",
  "DEF-spine003": "upperChest",
  "DEF-neck": "neck",
  "DEF-head": "head",
  "DEF-shoulderL": "leftShoulder",
  "DEF-upper_armL": "leftUpperArm",
  "DEF-forearmL": "leftLowerArm",
  "DEF-handL": "leftHand",
  "DEF-thumb.01L": "leftThumbMetacarpal",
  "DEF-thumb.02L": "leftThumbProximal",
  "DEF-thumb.03L": "leftThumbDistal",
  "DEF-f_index.01L": "leftIndexProximal",
  "DEF-f_index.02L": "leftIndexIntermediate",
  "DEF-f_index.03L": "leftIndexDistal",
  "DEF-f_middle.01L": "leftMiddleProximal",
  "DEF-f_middle.02L": "leftMiddleIntermediate",
  "DEF-f_middle.03L": "leftMiddleDistal",
  "DEF-f_ring.01L": "leftRingProximal",
  "DEF-f_ring.02L": "leftRingIntermediate",
  "DEF-f_ring.03L": "leftRingDistal",
  "DEF-f_pinky.01L": "leftLittleProximal",
  "DEF-f_pinky.02L": "leftLittleIntermediate",
  "DEF-f_pinky.03L": "leftLittleDistal",
  "DEF-shoulderR": "rightShoulder",
  "DEF-upper_armR": "rightUpperArm",
  "DEF-forearmR": "rightLowerArm",
  "DEF-handR": "rightHand",
  "DEF-thumb01R": "rightThumbMetacarpal",
  "DEF-thumb02R": "rightThumbProximal",
  "DEF-thumb03R": "rightThumbDistal",
  "DEF-f_index01R": "rightIndexProximal",
  "DEF-f_index02R": "rightIndexIntermediate",
  "DEF-f_index03R": "rightIndexDistal",
  "DEF-f_middle01R": "rightMiddleProximal",
  "DEF-f_middle02R": "rightMiddleIntermediate",
  "DEF-f_middle03R": "rightMiddleDistal",
  "DEF-f_ring01R": "rightRingProximal",
  "DEF-f_ring02R": "rightRingIntermediate",
  "DEF-f_ring03R": "rightRingDistal",
  "DEF-f_pinky01R": "rightLittleProximal",
  "DEF-f_pinky02R": "rightLittleIntermediate",
  "DEF-f_pinky03R": "rightLittleDistal",
  "DEF-thighL": "leftUpperLeg",
  "DEF-shinL": "leftLowerLeg",
  "DEF-footL": "leftFoot",
  "DEF-toeL": "leftToes",
  "DEF-thighR": "rightUpperLeg",
  "DEF-shinR": "rightLowerLeg",
  "DEF-footR": "rightFoot",
  "DEF-toeR": "rightToes",
};
